// React/crud/src/components/Home.jsx
import React, { useEffect, useState } from "react";
import Col from "react-bootstrap/Col";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import { useDispatch } from "react-redux";
import Swal from "sweetalert2";
import { deleteProduct, getAllProduct } from "../services/ProductService";
import ProductList from "./ProductList";
import { myAddCart } from "../store/CartSlice";

const Home = () => {
  const [proData, setProData] = useState([]);

  const dispatch = useDispatch();

  useEffect(() => {
    getAllProduct()
      .then((res) => {
        console.log(res.data);
        setProData(res.data);
      })
      .catch((err) => console.log(err));
  }, []);

  const delPro = (id) => {
    Swal.fire({
      title: "Do you want delete?",
      showDenyButton: true,
      confirmButtonText: "Ok",
      denyButtonText: `Cancel`,
    }).then((result) => {
      /* Read more about isConfirmed, isDenied below */
      if (result.isConfirmed) {
        deleteProduct(id)
          .then((res) => {
            let data = proData.filter((pro) => pro.id != id);
            setProData(data);
            Swal.fire("Product Delete", "", "success");
          })
          .catch((err) => console.log(err));
      }
    });
  };

  const addCart = (prod) => {
    if (localStorage.getItem("myCart") != undefined) {
      let flag = 0;

      let arr = JSON.parse(localStorage.getItem("myCart"));
      arr.forEach((Value, index) => {
        if (Value.id === prod.id) {
          arr[index].purchaseQuantity += 1;
          flag = 1;
        }
      });

      if (flag == 0) {
        let cartData = { ...prod, purchaseQuantity: 1 };
        arr.push(cartData);

        localStorage.setItem("myCart", JSON.stringify(arr));
        // myAddCart(arr);
        dispatch(myAddCart(arr));
        Swal.fire("Product added to cart");
      } else {
        localStorage.setItem("myCart", JSON.stringify(arr));
        // myAddCart(arr);
        dispatch(myAddCart(arr));
        alert("Product add cart successfully!");
      }
    } else {
      let arr = [];
      let cartData = { ...prod, purchaseQuantity: 1 };
      arr.push(cartData);
      localStorage.setItem("myCart", JSON.stringify(arr));
      Swal.fire("Product added to cart");
    }
  };

  return (
    <div>
      <h2> Latest Products</h2>
      <Container>
        <Row className="gap-4">
          {proData.map((product) => (
            <Col className="md-col-4" key={product.id}>
              <ProductList prod={product} delPro={delPro} addCart={addCart} />
            </Col>
          ))}
        </Row>
      </Container>
    </div>
  );
};

export default Home;

// Angular/crud_app/src/app/components/home/home.component.ts
import { Component , OnInit } from '@angular/core';
import { Product } from '../../product/product';
import { ProductsService } from '../../product/products.service';
import Swal from 'sweetalert2'
import { RouterLink } from '@angular/router';
 
 
 
@Component({
  selector: 'app-home',
  imports: [RouterLink],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements OnInit {
productData:Product[]=[];
 
constructor(private proser:ProductsService ){}
// addCart(id:any){
//   if(localStorage.getItem("mycart")!=undefined){
//      let data:any=localStorage.getItem("mycart");
//      let arr=JSON.parse(data);
//      if(arr.includes(id)){
//         Swal.fire("Already in a cart!");
//      }
//      else{
//        arr.push(id);
//        localStorage.setItem("mycart",JSON.stringify(arr));
//        Swal.fire("Add Cart Successfully!");
//      }
//   }
//   else{
//      let arr=[];
//      arr.push(id);
//      localStorage.setItem("mycart",JSON.stringify(arr));
//      Swal.fire("Add Cart Successfully!");
//   }
// }
addCart(id:any){
  if(localStorage.getItem("mycart")!=undefined){
    let data:any=localStorage.getItem("mycart");
    let arr=JSON.parse(data);
    if(arr.includes(id)){
      Swal.fire("Already In Cart")
    }else{
      localStorage.setItem("myCart",id)
    }
 
  }else{
    let arr:any[]=[];
    arr.push(id)
    localStorage.setItem("mycart" , JSON.stringify(arr));
    Swal.fire("Add Cart Successfully");
 
  }
}
ngOnInit():void{
  this.proser.getAllProduct().subscribe({
    next:(data:any)=>{
      console.log(data);
      this.productData=data;
    },
    error:(err)=>{
      console.log(err)
    }
  })
}
delPro(id:any){
  // if(confirm("Do u want to delete?")){
    //  this.proser.deleteProduct(id)
    //  .subscribe({
    //     next:(data:any)=>{
    //       this.productData=this.productData.filter((pro:any)=> pro.id!=id);
    //   //  this.router.navigateByUrl("/");//redirect to home
 
 
    //        alert("Product Deleted!");
    //     },
    //     error:(err)=>{
    //       console.log(err)
    //     }
    //  })
  // }
 
  Swal.fire({
    title: "Do you want to delete the product?",
    showDenyButton: true,
    // showCancelButton: true,
    confirmButtonText: "Delete",
    denyButtonText: `Cancel`
  }).then((result) => {
    /* Read more about isConfirmed, isDenied below */
    if (result.isConfirmed) {
      this.proser.deleteProduct(id)
      .subscribe({
         next:(data:any)=>{
           this.productData=this.productData.filter((pro:any)=> pro.id!=id);
       //  this.router.navigateByUrl("/");//redirect to home
       Swal.fire("Product is deleted");
 
            // alert("Product Deleted!");
         },
         error:(err)=>{
           console.log(err)
         }
      })
     
    } else if (result.isDenied) {
      Swal.fire("Product is not deleted", "", "info");
    }
  });
 
 }
}
 
<h2>latest products</h2>
 
<div class="row">
 
    @for(product of productData; track product.id ){
        <div class="col-md-4">
            <div class="card m-2 p-2" style="width: 18rem;">
               
                <div class="card-body">
                  <h5 class="card-title">{{product.name}}</h5>
                  <p class="card-text">
                    price :- Rs. {{product.price}}
                    Quantity :- {{product.quantity}}
                  </p>
                  <a [routerLink]="['editpro' , product.id]" class="btn btn-primary m-2">Edit</a>
                  <button class="btn btn-danger m-2" (click)="delPro(product.id)">Delete</button>
                </div>
              </div>
        </div>
    }
</div>
